README.md
=> Document /add_stumbles API call

README.md, leaderboard/contributors/serializers.py, leaderboard/contributors/tests.py, leaderboard/contributors/views.py, leaderboard/locations/migrations/0002_auto_20150715_2058.py, leaderboard/locations/models.py, leaderboard/locations/tests.py
- Update models
- Update serializers
- Update tests
- Add db migration
=> Use "easting" and "northing" as coordinate labels #12

README.md
=> Add /leaders to API documentation

leaderboard/contributors/tests.py, leaderboard/parsers.py, leaderboard/settings.py, leaderboard/utils/compression.py
- Parse Gzipped JSON
- Add test
=> Add gzip support for data contribution #1

README.md, leaderboard/contributors/migrations/0002_auto_20150717_1925.py, leaderboard/contributors/models.py, leaderboard/contributors/serializers.py, leaderboard/contributors/tests.py, leaderboard/settings.py
- Add time field to serializer
- Add date field to contribution
- Update tests
- Update documentation
=> Add time duration to contribution submission API #14

README.md, leaderboard/contributors/tests.py, leaderboard/contributors/urls.py, leaderboard/locations/models.py, leaderboard/locations/serializers.py, leaderboard/locations/tests/test_models.py, leaderboard/locations/tests/test_views.py, leaderboard/locations/urls.py, leaderboard/locations/views.py, leaderboard/settings.py, leaderboard/urls.py, requirements.txt
- Add Country serializer
- Add CountryList view
- Add tests
- Update docs
=> Add /get_countries API end point #16

README.md, leaderboard/contributors/tests.py, leaderboard/contributors/urls.py, leaderboard/contributors/views.py, leaderboard/settings.py, leaderboard/urls.py
- Add API call
- Add test
- Update docs
=> API endpoint for contribution config #11

README.md, leaderboard/contributors/models.py, leaderboard/contributors/serializers.py, leaderboard/contributors/tests.py, leaderboard/contributors/urls.py, leaderboard/contributors/views.py, leaderboard/locations/models.py, leaderboard/locations/tests/test_models.py, leaderboard/locations/tests/test_views.py
- Add Leader serializer
- Add country leaders view
- Add tests
- Update docs
=> Add country leaders API endpoint #8

leaderboard/fxa/client.py, leaderboard/fxa/tests/test_client.py, leaderboard/fxa/tests/test_views.py, leaderboard/fxa/urls.py, leaderboard/fxa/views.py, leaderboard/settings.py, leaderboard/urls.py
- Add FXA client
- Add FXA post registration redirect view
- Tests
=> Integrate FXA for User Accounts #28

README.md, leaderboard/contributors/tests.py, leaderboard/contributors/urls.py, leaderboard/contributors/views.py
- Update urls
- Update view
- Update tests
- Update docs
=> Use ISO country code instead of db id #33

README.md, leaderboard/contributors/tests.py, leaderboard/contributors/urls.py, leaderboard/contributors/views.py
- Add view
- Add tests
- Update docs
=> Add all leaders API #40

README.md, leaderboard/contributors/tests.py, leaderboard/settings.py
- Add settings
- Update tests
- Update docs
=> Paginate API calls #42

leaderboard/contributors/models.py, leaderboard/contributors/serializers.py, leaderboard/contributors/tests/test_models.py, leaderboard/contributors/tests/test_views.py, leaderboard/contributors/views.py
- Add custom queryset
- Update views
- Update tests
=> Move observations annotation to model manager #46

leaderboard/contributors/tests/test_views.py, leaderboard/contributors/views.py
=> Add 404 to Country Leaders #50

leaderboard/contributors/migrations/0003_auto_20150810_1902.py, leaderboard/contributors/models.py, leaderboard/contributors/serializers.py, leaderboard/contributors/tests/test_models.py, leaderboard/contributors/tests/test_views.py, leaderboard/contributors/views.py, leaderboard/fxa/client.py, leaderboard/fxa/tests/test_views.py, leaderboard/fxa/views.py
=> Use FXA for submission Contributor #47

leaderboard/contributors/serializers.py, leaderboard/contributors/tests/test_views.py, leaderboard/contributors/views.py, leaderboard/fxa/authenticator.py, leaderboard/fxa/client.py, leaderboard/fxa/tests/test_authenticator.py
- Add OAuthTokenAuthentication
- Add OAuthTokenAuthentication tests
- Use OAuthTokenAuthentication in Contribution views
=> Use DRF Authentication #58

leaderboard/contributors/tests/test_views.py, leaderboard/parsers.py
=> Update content-encoding header #60

README.md, leaderboard/contributors/migrations/0004_auto_20150825_1957.py, leaderboard/contributors/models.py, leaderboard/contributors/serializers.py, leaderboard/contributors/tests/test_views.py, leaderboard/contributors/urls.py, leaderboard/contributors/views.py
- Add a serializer/view
- Set name as unique
- Add tests
- Update docs
=> Add a contributor name API #62

leaderboard/contributors/models.py, leaderboard/leaders/tests/test_views.py
- Update observations filter
- Update test
=> Empty Contributor should not appear #81

README.md, leaderboard/contributors/migrations/0005_auto_20150831_1908.py, leaderboard/contributors/models.py, leaderboard/contributors/tests/test_models.py, leaderboard/leaders/serializers.py, leaderboard/leaders/tests/test_views.py, leaderboard/leaders/views.py
- Create ContributorCountryRank model
- Populate it using compute_ranks
- Update serializers to use ContributorCountryRank
- Add/update tests
- Update docs
=> Add rank to leader calls #76

README.md, leaderboard/contributors/models.py, leaderboard/leaders/serializers.py, leaderboard/leaders/tests/test_views.py, leaderboard/leaders/urls.py, leaderboard/leaders/views.py
- Add view
- Add serializers
- Add tests
- Update docs
=> Add a profile call #64

README.md, leaderboard/locations/models.py, leaderboard/locations/serializers.py, leaderboard/locations/tests/test_views.py, leaderboard/locations/urls.py, leaderboard/locations/views.py, leaderboard/settings.py, leaderboard/urls.py, requirements.txt
This reverts commit 6dc0b6793cd3adb39d473603b454385c9119ce93.
Conflicts:
README.md
leaderboard/settings.py
leaderboard/urls.py
=> Revert "Remove Country List API #32"

leaderboard/static/js/react.leaders.js, leaderboard/static/js/react.map.js, leaderboard/static/lib/fetch/LICENSE, leaderboard/static/lib/fetch/MAINTAINING.md, leaderboard/static/lib/fetch/Makefile, leaderboard/static/lib/fetch/README.md, leaderboard/static/lib/fetch/bower.json, leaderboard/static/lib/fetch/examples/index.html, leaderboard/static/lib/fetch/fetch.js, leaderboard/static/lib/fetch/package.json, leaderboard/static/lib/fetch/script/phantomjs, leaderboard/static/lib/fetch/script/saucelabs, leaderboard/static/lib/fetch/script/saucelabs-result, leaderboard/static/lib/fetch/script/saucelabs-start, leaderboard/static/lib/fetch/script/saucelabs-status, leaderboard/static/lib/fetch/script/server, leaderboard/static/lib/fetch/script/test, leaderboard/static/lib/fetch/test/.gitignore, leaderboard/static/lib/fetch/test/.jshintrc, leaderboard/static/lib/fetch/test/test-worker.html, leaderboard/static/lib/fetch/test/test.html, leaderboard/static/lib/fetch/test/test.js, leaderboard/static/lib/fetch/test/worker.js, leaderboard/templates/base.html, leaderboard/templates/home/landing.html
- Add fetch polyfill
- Use fetch
- Remove jquery
=> Use fetch API #122

README.md, leaderboard/locations/models.py, leaderboard/locations/serializers.py, leaderboard/locations/tests/test_views.py, leaderboard/locations/views.py, leaderboard/static/js/leaderboard.js, leaderboard/static/js/react.leaderboard.js, leaderboard/static/js/react.map.js, leaderboard/templates/home/landing.html
- Request country info at init time
- Only highlight countries which appear in that list
- Update serializer to include leaders url
=> Highlight countries which have data #103

leaderboard/static/js/react.leaderboard.js, leaderboard/static/js/react.leaders.js, leaderboard/static/js/react.map.js
- Query country list at init time
- Add country drop down
- Add a global 'selected country' state
- Set map highlight by selected country
- Set country dropdown by selected country
- Snap to selected country
=> Change country name to drop down #98

leaderboard/locations/views.py
- Only query country fields that are needed
=> Improve performance of /countries/ API call #136

gulpfile.js, leaderboard/static/js/leaderboard.js, leaderboard/static/js/leaderboard.react.js, leaderboard/static/js/leadermap.react.js, leaderboard/static/js/leadertable.react.js, leaderboard/templates/home/landing.html, package.json
- Add react to npm requirements
- Import per file
- Update to React 1.4
=> Import react in each file #142

leaderboard/static/js/cachedfetch.js, leaderboard/static/js/leaderboard.react.js, leaderboard/static/js/leadermap.react.js, leaderboard/static/js/leadertable.react.js, leaderboard/templates/home/landing.html
- add cachedFetch library
- convert all remote requests to use it
=> Use cachedFetch for all AJAX requests #147

leaderboard/static/js/leaderboard.react.js, leaderboard/static/js/leadermap.react.js, leaderboard/static/js/leaderskey.js, leaderboard/static/js/leadertable.react.js, leaderboard/static/js/parseurl.js
- Store iso2 and offset
- Compute urls based on iso2 and offset
=> Remove URL from Leaderboard component state #149

leaderboard/static/js/cachedfetch.js, leaderboard/static/js/leaderboard.react.js, leaderboard/static/js/leadermap.react.js, leaderboard/static/js/leaderskey.js, leaderboard/static/js/leadertable.react.js
- Store currently selection in browser location
- Immediately jump to region and offset if specified during load
=> Store region and offset in browser location #104

README.md, leaderboard/leaders/serializers.py, leaderboard/leaders/tests/test_views.py, leaderboard/static/css/leaderboard.css, leaderboard/static/js/cachedfetch.js, leaderboard/static/js/leaderboard.react.js, leaderboard/static/js/leadermap.react.js, leaderboard/static/js/leaderprofile.react.js, leaderboard/static/js/leadertable.react.js, leaderboard/static/less/leaderboard.less, leaderboard/templates/home/landing.html
- Clicking a username opens the user's Profile
- Clicking a country in the Profile jumps to that Country's leaderboard
=> Add Profile Page #131

Dockerfile
Saves some intermediate steps/images. Smaller end-result (not much, but a bit).
=> make Dockerfile work more as we expect it to in other cloudops projects

leaderboard/contributors/migrations/0008_remove_contributor_email.py, leaderboard/contributors/migrations/0009_auto_20151123_2030.py, leaderboard/contributors/models.py, leaderboard/contributors/tests/test_models.py, leaderboard/contributors/tests/test_views.py, leaderboard/fxa/tests/test_views.py
- Remove unused email field
- Remove duplicate constraint on name field
- Add unit test
=> Remove email to allow multiple FXA signins #186

Dockerfile, scripts/start_leaderboard.sh
- Add startup script which copies static files to a public shared folder
- Add collectstatic to docker build step
=> Add a startup script #204

leaderboard/contributors/models.py, leaderboard/contributors/tests/test_models.py
- Add new tests
- Change aggregation logic to compute in memory
- Remove ContributorQuerySet
=> Remove contributions after computing aggregates #191

README.md, leaderboard/fxa/tests/test_views.py, leaderboard/fxa/urls.py, leaderboard/fxa/views.py
- Add view
- Add tests
- Update docs
=> Add an FXA configuration request endpoint #210

README.md, leaderboard/fxa/tests/test_views.py, leaderboard/fxa/views.py
- Add parameter to JSON response
- Update test
- Update docs
=> Add redirect_uri to fxa config #210

leaderboard/fxa/tests/test_views.py, leaderboard/fxa/urls.py, leaderboard/fxa/views.py, leaderboard/settings.py
=> Add FXA Login Redirect #189

README.md, leaderboard/home/tests.py, leaderboard/home/urls.py, leaderboard/home/views.py, leaderboard/settings.py
- Query OS environment at startup time
- Statically host parameters through api view
- Add test
- Add docs
=> Add a __version__ endpoint #185

README.md, leaderboard/home/tests.py, leaderboard/home/urls.py, leaderboard/home/views.py
- Add a view that tests if it can connect to the db
- Add test
- Add docs
=> Add a __heartbeat__ endpoint #184

leaderboard/settings.py, leaderboard/settings_local.py.ex, requirements.txt
- Add raven
- Add raven settings
=> Add Sentry Monitoring #211

README.md, leaderboard/leaders/tests/test_views.py, leaderboard/leaders/views.py
- Update view
- Add test
- Upate docs
=> Hide users with no display name #237

leaderboard/home/tests.py, leaderboard/home/urls.py, leaderboard/home/views.py, leaderboard/settings.py
This reverts commit 9ba78193902c8469ae2d914507da673810888bf9.
Conflicts:
README.md
leaderboard/home/tests.py
leaderboard/home/urls.py
leaderboard/home/views.py
leaderboard/settings.py
=> Revert "Add a __version__ endpoint #185"

.gitignore, Dockerfile, leaderboard/home/tests.py, leaderboard/home/urls.py, leaderboard/home/views.py, leaderboard/settings.py, scripts/echo_version_json.sh
- Add view
- Add tests
- Add setting
- Add script to generate version.json
=> Add __version__ endpoint #185

leaderboard/settings.py, scripts/setup_countries.sh
- Add script
- Remove unnecessary setting which breaks import
=> Add country shape import script #247

leaderboard/contributors/serializers.py, leaderboard/contributors/tests/test_views.py, leaderboard/locations/management/commands/load_countries.py, leaderboard/locations/migrations/0006_auto_20160208_2050.py, leaderboard/locations/models.py, leaderboard/locations/tests/test_models.py, leaderboard/settings.py
- Store countries as WGS84
- Receive coordinates as Web Mercator and convert immediately to WGS84
- Add test
=> Store all geometries as WGS84 #253

leaderboard/settings_local.py.ex, leaderboard/wsgi.py, requirements.txt
=> Add newrelic support

circle.yml, leaderboard/settings.py
Dockerflow migration to circle
@jaredkerim r?
=> Dockerflow migrate

README.md
Fixes the URLs in the readme docs.
=> readme: add location- to leaderboard in subdomain
